var a = 100;
var b = 'Puja';
var c = true;
var d = 100;
var obj = { name: "satish", email: 'puja.pandey@gmail.com' };
console.log(a);
console.log(b);
console.log(c);
console.log(d);
console.log(obj);
