var a:number=100;
var b: string= 'Puja';
var c: boolean = true;
var d: any = 100;
var obj: Object = {name: "satish", email: 'puja.pandey@gmail.com'};
console.log(a);
console.log(b);
console.log(c);
console.log(d);
console.log(obj);